apiVersion: v1
kind: Service
metadata:
  name: {{ include "hometask.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "hometask.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "hometask.selectorLabels" . | nindent 4 }}
